### ISSUE TITLE
Cannot run a specific activity

### ISSUE THREAD

**Issue by asmeurer** [ergs/rever#16]
If I use `rever -e activity` I get a KeyError.

```
$rever 1.1.rc1 -e test
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/rever", line 3, in <module>
    main()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/rever/main.xsh", line 151, in main
    env_main(args=args)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/rever/main.xsh", line 140, in env_main
    running_activities(ns)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/rever/main.xsh", line 45, in running_activities
    $RUNNING_ACTIVITIES = acts[entry]
KeyError: 'test'
```

**Comment by scopatz** [comment]
What does the rever.xsh file look like?

**Comment by asmeurer** [comment]
https://github.com/sympy/sympy/blob/1.1/release/rever.xsh

Seeing this now for `GitHub_release`.

**Comment by asmeurer** [comment]
I printed the `acts` dictionary, it's empty.

**Comment by scopatz** [comment]
You are supposed to use `rever -a name` to run a specific activity
