### ISSUE TITLE
KeyError: 'Unknown environment variable: $SHELL'

### ISSUE THREAD

**Issue by asmeurer** [ergs/rever#22]
I have `$XONSH_SHOW_TRACEBACK = True` and I get this printed a lot (it doesn't cause it to fail).

```pytb
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13063, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12885, in proxy_two
    return f(args, stdin)
  File "/opt/conda/lib/python3.6/site-packages/xontrib/xonda.xsh", line 92, in _xonda
    _activate(args[1])
  File "/opt/conda/lib/python3.6/site-packages/xontrib/xonda.xsh", line 70, in _activate
    $SHELL)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 16621, in __getitem__
    raise KeyError(e.format(key))
KeyError: 'Unknown environment variable: $SHELL'
```

**Comment by scopatz** [comment]
This seems to be a xonda error.  Please report it there. Thanks!

**Comment by asmeurer** [comment]
https://github.com/gforsyth/xonda/issues/13
