### ISSUE TITLE
Tag shorthand without <tag>

### ISSUE THREAD

**Issue by CJ-Wright** [ergs/rever#46]
It seems I ran into an error
```python
christopher@christopher-ubuntu ~/dev/xpdAcq tag $ rever 0.6.0
Activity 'version_bump' has already been completed!
activity-start:tag:starting activity tag
Updated tag '0.6.0' (was 066fd6e)
fatal: tag shorthand without <tag>
activity-error:tag:activity failed with execption:
Traceback (most recent call last):
  File "/home/christopher/dev/rever/rever/activity.xsh", line 54, in __call__
    self.func(*args, **kwargs)
  File "/home/christopher/dev/rever/rever/activities/tag.xsh", line 40, in _func
    vcsutils.push(remote, target)
  File "/home/christopher/dev/rever/rever/vcsutils.xsh", line 30, in vcs_dispatcher
    return func(*args, **kwargs)
  File "/home/christopher/dev/rever/rever/vcsutils.xsh", line 130, in git_push
    git push @(remote) @(target)
  File "/home/christopher/mc/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19208, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/christopher/mc/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19171, in run_subproc
    command.end()
  File "/home/christopher/mc/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13721, in end
    self._end(tee_output=tee_output)
  File "/home/christopher/mc/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13740, in _end
    self._raise_subproc_error()
  File "/home/christopher/mc/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13850, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'push', 'git@github.com:CJ-Wright/xpdAcq.git', 'tag']' returned non-zero exit status 128
rewinding to 10ed3b1f15a093e964788e61d3ab933c95a98619
```
Thoughts on what I could be doing wrong?
(If this is not me just using the software wrong we may want a more verbose error)

**Comment by CJ-Wright** [comment]
Error was between keyboard and chair :sheep:

**Comment by scopatz** [comment]
For posterity, this seems to be a git bug
